[tool.black]
line-length = 120
[tool.ruff]
line-length = 120

[project]
name = "clean-pycontrol"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mpremote>=1.26.1",
    "numpy>=2.3.4",
    "pyqt6>=6.10.0",
    "pyqtgraph>=0.13.7",
    "pyserial>=3.5",
]
